-- 001_initial.sql
-- Canonical from-scratch schema for notes-api, captured from the live DB.
-- pgcrypto provides crypt()/gen_salt() used for password hashing in users.py.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL
);

CREATE TABLE notes (
    id           text NOT NULL PRIMARY KEY,
    title        text NOT NULL,
    body         text NOT NULL,
    parent_id    text,
    user_id      integer NOT NULL REFERENCES users(id),
    color        text,
    tag          text,
    last_updated timestamp without time zone NOT NULL DEFAULT now(),
    deleted      boolean NOT NULL DEFAULT false
);

-- Redundant with the primary key on notes(id); kept so fresh installs match the
-- live DB exactly (originally created by the old ensure_sync_schema()).
CREATE UNIQUE INDEX notes_id_key ON notes (id);
